### PR TITLE
feat: update to 17.5.0 and backgrounding support

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
- https://jira.appcelerator.org/browse/TIMOB-27934
- https://jira.appcelerator.org/browse/TIMOB-27896

**Summary:**
- Updated play services library from `17.1.1` to `17.5.0`.
- Changed `makeGooglePlayServicesAvailable()` method to use native implementation.
  * Now shows Google's standard dialog if Play Services needs to be updated.
  * Couldn't use native implementation before because backing out of the activity that was hosting this dialog used to crash on Google's end. Google has now fixed it.
- Updated module's bootstrap to use new `showUI()` method.
  * This supports our new "run-in-background" feature. See: [TIMOB-27896](https://jira.appcelerator.org/browse/TIMOB-27896)
  * We show bootstrap's UI every time a new UI session begins for the same JS runtime.

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
LGTM!

**Comment by garymathews** [comment]
Need to fix conflicts, may want to bump Jenkins build SDK

**Review by garymathews — APPROVED** [review]

**Comment by jquick-axway** [comment]
Updated PR:
- Updated to Google Play Services 17.5.0.
- Modified bootstrap to support [TIMOB-27896](https://jira.appcelerator.org/browse/TIMOB-27896) backgrounding feature dynamically.
- Reverted `minsdk` from `9.3.0` to `9.0.0`.

**Review by garymathews — APPROVED** [review]
LGTM!

**Pull request merged**
