### PR TITLE
[TIMOB-25665] Update libraries to 11.8.0, add missing libraries

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA**: https://jira.appcelerator.org/browse/TIMOB-25665

**Prerelease**: https://github.com/appcelerator-modules/ti.playservices/releases/tag/v11.8.0

## Added:
- `play-services-auth-api-phone`
- `play-services-panorama`
- `play-services-places`
- `play-services-safetynet`

## Updated (11.0.1 -> 11.8.0):
- `play-services-ads-lite`
- `play-services-analytics-impl`
- `play-services-auth`
- `play-services-auth-base`
- `play-services-awareness`
- `play-services-base`
- `play-services-basement`
- `play-services-cast`
- `play-services-gcm`
- `play-services-identity`
- `play-services-iid`
- `play-services-location`
- `play-services-maps`
- `play-services-nearby`
- `play-services-task`
- `play-services-wallet`

## Deleted (Not listed anymore):
- `play-services-appinvite`
- `play-services-cast-framework`

### CODE REVIEW

**Comment by jquick-axway** [comment]
@hansemannn, let's hold off on upgrading the Google Play Services library right now. You can see my reasons [here](https://jira.appcelerator.org/browse/TIMOB-25665?focusedCommentId=433108&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-433108).

**Comment by jonesdhtx** [comment]
Google seems to indicate that concern is unwarranted?

**Comment by jquick-axway** [comment]
@jonesdhtx, unfortunately, this issue does still happen. I've seen it. It's best to use Google Play Services 2-3 versions behind until this has been resolved.

The goal for the near future is to auto-check/download the newest version on app startup before running the "app.js" script. Once we do that, we can then use the newest library version without issue.

**Comment by hansemannn** [comment]
So..we are currently 4 (!) major versions behind other frameworks. Can someone please update play-services to latest and let developers decide to take it or not? This is absolutely frustrating.

**Comment by garymathews** [comment]
Updated to `16.1.0`: https://github.com/appcelerator-modules/ti.playservices/releases/tag/16.1.0

**Pull request closed without merging**
