### PR TITLE
build: try to publish to npm

### PR DESCRIPTION
**Pull request by sgtcoolguy**
WORK IN PROGRESS

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
This is crashing on app launch (during Karma testing), see the error output below...

It seems as of Ads SDK 17+ users must add some metadata to their AndroidManifest.xml or it'll crash. We're already shipping this version out there, so I'm not sure why I/we hadn't run into this before...


```
24 18500 18500 D AndroidRuntime: Shutting down VM
08-30 14:50:26.024 18500 18500 E AndroidRuntime: FATAL EXCEPTION: main
08-30 14:50:26.024 18500 18500 E AndroidRuntime: Process: ti.playservices.karmarunner, PID: 18500
08-30 14:50:26.024 18500 18500 E AndroidRuntime: java.lang.RuntimeException: Unable to get provider com.google.android.gms.ads.MobileAdsInitProvider: java.lang.IllegalStateException: 
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 
08-30 14:50:26.024 18500 18500 E AndroidRuntime: ******************************************************************************
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * should follow the instructions here:                                       *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * to add a valid App ID inside the AndroidManifest.                          *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * Google Ad Manager publishers should follow instructions here:              *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: ******************************************************************************
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6396)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at android.app.ActivityThread.installContentProviders(ActivityThread.java:5938)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5853)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at android.app.ActivityThread.access$1100(ActivityThread.java:199)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1650)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:193)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6669)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: Caused by: java.lang.IllegalStateException: 
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 
08-30 14:50:26.024 18500 18500 E AndroidRuntime: ******************************************************************************
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * The Google Mobile Ads SDK was initialized incorrectly. AdMob publishers    *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * should follow the instructions here:                                       *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * https://googlemobileadssdk.page.link/admob-android-update-manifest         *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * to add a valid App ID inside the AndroidManifest.                          *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * Google Ad Manager publishers should follow instructions here:              *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: * https://googlemobileadssdk.page.link/ad-manager-android-update-manifest.   *
08-30 14:50:26.024 18500 18500 E AndroidRuntime: ******************************************************************************
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at com.google.android.gms.internal.ads.zzxi.attachInfo(com.google.android.gms:play-services-ads-lite@@18.2.0:27)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at com.google.android.gms.ads.MobileAdsInitProvider.attachInfo(com.google.android.gms:play-services-ads-lite@@18.2.0:3)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	at android.app.ActivityThread.installProvider(ActivityThread.java:6391)
08-30 14:50:26.024 18500 18500 E AndroidRuntime: 	... 10 more
```

**Comment by hansemannn** [comment]
Thats definitely not required for this module. Maybe the test app also adds other modules like `Ti.Admob`? Because that one *does* require these flags.

**Comment by sgtcoolguy** [comment]
The test app should simply be loading the specific module we're building and no others.

Presumably this is a result of no longer blacklisting/skipping the ads-lite AAR, @ypbnv ?

**Comment by ypbnv** [comment]
@sgtcoolguy Yes, I believe having play-services-ads-lite.jar in the list of dependencies is the reason it crashes. After an update from Admob the play-services-ads-lite started to require users to provide their Admob ID in the applications manifest even if the library is only added and not used/referenced anywhere. Adding the jar back to the black list should solve this. It will be added in ti.admob.

**Pull request merged**
